/* eslint-disable */
export default {
  common: {
    loading: '加载中...',
    loading_no_dots: '加载中',
    load: '加载',
    loading_asset_data: '加载资产数据中...',
    create: '创建',
    creating: '创建中',
    generate: '生成',
    generating: '生成中',
    connect: '连接',
    connecting: '连接中',
    connected: '已连接',
    buy: '购买',
    buying: '购买中',
    enable: '开启',
    enabling: '开启中',
    exchange: '兑换',
    exchanging: '兑换中',
    supply: '存款',
    supplying: '存款中',
    borrow: '借款',
    borrowing: '借款中',
    supplied: '已存入',
    withdraw: '提现',
    withdrawing: '提现中',
    transfer: '转移',
    transferring: '转移中',
    boost: '加仓',
    boosting: '加仓中',
    repay: '还款',
    repaying: '还款中',
    payback: '还款',
    sending: '发送中',
    send: '发送',
    subscribe: '订阅',
    subscribing: '订阅中',
    paying_back: '还款中',
    add_collateral: '添加抵押',
    adding_collateral: '添加抵押中',
    migrate: '迁移',
    migrating: '迁移中',
    move: '移动',
    moving: '移动中',
    after: '之后',
    saver: '储蓄',
    manage: '管理',
    success: '成功!',
    coming_soon: '%feature 即将推出...',
    short: '做空',
    leverage: '杠杆',
    in_a_week: '一周',
    in_a_month: '一个月',
    in_a_year: '一年',
    price: '价格',
    collateral_factor: '抵押因子',
    market_liquidity: '市场流通数量',
    utilization: '使用率',
    market_info: '市场信息:',
    insured: '已担保:',
    supply_rate: '存款利率:',
    borrow_rate: '借款利率:',
    choose_asset: '选择资产:',
    stability_fee: '稳定费用:',
    liquidation_price: '清算价格:',
    current_slippage: '当前价格波动:',
    action: '操作',
    overview: '概览',
    ratio: '抵押率',
    pages: '页面:',
    choose: '选择',
    debt: '债务',
    account_type: '账户类型:',
    path: '路径:',
    minimum_amount: '最低数量:',
    from_token: '从 %token',
    to_token: '到 %token',
    to: '到',
    from: '从',
    amount: '数量',
    name: '名称',
    balance: '余额',
    approve: '同意',
    approving: '同意中',
    approved: '已同意',
    close: '关闭',
    closing: '关闭中',
    logging_in: '登录中...',
    safe: '安全',
    risky: '一般风险',
    gamble: '高风险',
    amount_of_token: '%token 数量:',
    token_amount_in: '%second_token 中 %first_token 数量:',
    executing_action: '执行操作',
    new_owner: '新属主',
    welcome_back: '欢迎回来!',
    contact_us: '联系我们',
    token_debt: '%token 债务',
    with: '具有',
    at_price: '价格',
    automate: '自动运行',
    reminder: '提醒',
    info: '信息',
    legacy: 'Legacy',
    live: '在线',
    custom_type: '自定义类型',
    max: '最大 %value',
    email: '邮箱',
    email_address: '邮箱地址',
    follow_us: '关注我们:',
    protocols: '协议',
    wallets: '钱包',
    repay_to: '还款至',
    ratio_over: '抵押率超过',
    boost_to: '加仓至',
    current_price: '当前价格',
    collateral: '抵押',
    collateral_in: '已抵押',
    set_up: '设置',
    how_does_it_work: '它是如何工作的?',
    history: '历史',
    type: '类型',
    date: '日期',
    transaction: '交易',
    load_more: '加载更多',
    protection: '保护',
    update: '更新',
    updating: '更新中',
    disable: '禁用',
    disabling: '禁用中',
    advanced: '高级',
    cancel: '取消',
    message: '消息',
    accepts: '接受',
    import: '导入',
    importing: '导入中',
    soon: '即将',
    no_notifications_received: '未收到通知.',
    go_back_to_dashboard: '回到面板',
    your_feedback_helps_us: '您的反馈将有助于我们改善DeFi Saver',
    create_dsproxy: '创建DSProxy',
  },
  account: {
    connect_wallet: '连接您的钱包:',
    connect_message: '连接 %item',
    secure_way: '这是一种安全访问您钱包的方式',
    account_connected: '该账户目前已连接',
    load_accounts: '%status 更多账户',
    user_wallet: '用户钱包',
    user_wallet_info: '您在智能储蓄中使用的资金将由您自己的用户钱包控制。该钱包是标准的MakerDAO DSProxy钱包，用于更轻松地集成借贷协议',
    user_wallet_info_2:'由于使用了用户钱包(DSProxy),您在其它面板上如Compound将无法查看您的资产',
    user_wallet_address_info: '请不要向该地址直接转账.',
    create_user_wallet: '创建用户钱包',
    user_wallet_information: '用户钱包信息',
    create_ds_proxy: '创建DSProxy',
    account_found: ' %account 中发现 %type 类型账号',
  },
  maker: {
    approve_maker: '同意MakerDao',
    approving_maker_for: '同意MakerDao使用 %label',
    approve_maker_description: '为了让您的Compound资产和CDP直接交互，您首先需要开启CDP交互功能',
    create_cdp: '创建CDP',
    loading_cdp: '加载CDP...',
    get_cdp_info: '获取您的CDP信息...',
    cdp_id: '当前CDP ID',
    cdp_state: '当前CDP状态: %current%',
    cdp_lower_bound: ' 若抵押率低于 %lower_bound% ，则还款至 %lower_bound_target%',
    cdp_upper_bound: '若抵押率高于 %upper_bound% ，则加仓至 %upper_bound_target%',
    no_cdp_1: '您尚未拥有CDP. 你是否愿意 ',
    no_cdp_2: '现在创建一个?',
    no_cdp_found: 'CDP未找到',
    close_cdp: '关闭CDP',
    transfer_cdp: '转移CDP',
    migrate_cdp: '迁移CDP',
    transfer_cdp_description: '通过将您的CDP转移至新的地址，你将失去当前地址地所有权',
    create_cdp_description: '创建一个CDP可以让您通过抵押ETH方式获得Dai',
    minimum_ratio: '接受的最低抵押率为150％，我们建议该比率高于200％，以确保CDP不会被清算',
    ratio_warning: '您的抵押率必须不低于150％',
    pay_stability_debt: '用DAI支付稳定债务:',
    generate_description: '从您的CDP中获得更多的Dai',
    withdraw_description: '从您CDP中提现抵押的ETH',
    boost_description: '通过一次交易，便可使用Dai购买ETH并添加到您的CDP中',
    boost_modal_description: '加仓将会花费你的Dai购买更多的ETH，同样只需一次交易这会增加您CDP中的ETH数量',
    payback_description: '偿还您CDP中的Dai债务',
    payback_modal_description: '偿还债务会降低您的清算价格在用Dai偿还债务时，您还需要用MKR支付管理费用',
    add_collateral_description: '向您的CDP添加更多ETH抵押',
    repay_description: '只需一次交易，就可花费ETH购买Dai来偿还CDP中的部分债务',
    repay_modal_description: '还款将花费您CDP中的ETH购买Dai来偿还债务，同样只需一次交易。这将提高您的清算价格和抵押率',
    all_debt_repay: '所有债务将被偿还，多余的Dai将退还给您',
    migrate_description: '通过迁移，您可以与DeFi Saver平台进行交互，可以使用标准的MakerDAO DSProxy接口，还可以与其他CDP平台进行交互',
    saver_subscribe: '订阅CDP自动运行',
    saver_unsubscribe: '取消订阅CDP自动运行',
    no_cdp_blocker: '我们找不到与此帐户关联的CDP，请确保您使用的帐户正确。您现在要创建一个新的CDP吗？',
    amount_of_dai_generated: 'CDP产生的Dai数量',
    cdp_collateral_peth: '用户CDP中的抵押将以PETH形式存储',
    stability_fee_in: '稳定费用',
    stability_fee_paid_in: '可以通过MKR或Dai支付稳定费用',
    cdp_automation: 'CDP自动运行',
    cdp_automation_description: '使你的CDP保持在某一比率来避免被清算或者根据市场变化增加杠杆',
    automation_history_log_description: '以下是DeFi Saver所执行的与您CDP相关所有活动的历史日志',
    ratio_change: '抵押率变化',
    no_actions_executed: '目前尚未执行任何操作',
    cdp_automation_status: 'CDP自动化状态',
    cdp_automation_active_account: '该帐户的CDP自动运行功能目前处于激活状态，该图显示了您当前的配置',
    keep_ratio_at: '使抵押率保持在:',
    if_ratio_bellow: '若抵押率降至:',
    repay_it_to: '还款至:',
    will_hit_ratio_at: '将在 %value 时达到此抵押率',
    if_ratio_goes_over: '若抵押率超过:',
    boost_it_to: '加仓至:',
    cdp_automation_setup: 'CDP自动运行设置',
    cdp_automation_setup_description: '一旦开启CDP自动运行，DeFi Saver将监视您的CDP抵押率，并在您的CDP到达设置的较低抵押率时自动偿还债务，或者到达较高抵押率时自动加仓。您只需简单地输入目标抵押率，或按照如下进行手动配置',
    dai_debt_at_least: 'Dai债务需要至少为 %value 才可开启CDP自动运行',
    loading_saver_data: '加载Saver数据...',
    automatic_boost_will_be_triggered: '使用当前参数并开启自动运行将会触发自动加仓',
    automatic_repay_will_be_triggered: '使用当前参数并开启自动运行将会触发自动还款',
    automation_form_beta_warning: '此功能处于测试阶段，使用风险自负',
    import_description: '使用此工具会将您的CDP从专门的InstaDApp代理钱包迁移到标准Maker DSProxy钱包。 \n\n' +
      '通过迁移，您可以访问我们的高级功能，例如自动化运行，加仓和还款，以及访问其他仪表板，例如Maker的CDP Portal和Zerion。\n\n' +
      '  一旦您将CDP迁移至DSProxy，你将无法再次使用InstaDapp,除非您再将CDP迁移回去
	  ',
    import_cdp: '导入CDP',
    migrating_cdp_from_instadapp: '从InstaDApp迁移CDP',
    cdp_managed_by_instadapp: '该CDP目前位于InstaDApp代理钱包中.',
    why_disabling_automation: '您能告诉我们为什么要禁用自动运行功能吗?',
    saver_unsubscribe_reason_1: '我想在当前的自动运行配置之外进行调整',
    saver_unsubscribe_reason_2: '我认为该功能不够安全',
    saver_unsubscribe_reason_3: '我不确定这能不能避免我的CDP被清算',
    saver_unsubscribe_reason_4: 'CDP抵押率变化超出我的预料',
    saver_unsubscribe_reason_5: '其它(请简单描述):',
    liquidation_protection_if_bellow: '清算保护: 若低于',
    repay_to: 'repay to',
    leverage_increase_if_above: '增加杠杆: 若高于',
  },
  compound: {
    supply_to_cdp_title: '向CDP存入',
    supply_from_cdp_title: '从CDP取出',
    supply_to_cdp_description: '通过花费您在Compound中的Dai资产来偿还您的CDP债务',
    supply_from_cdp_description: '从CDP中获得Dai并添加到您的Compound资产',
    supply_info: '存入的金额+赚取的利息',
    supply_assets_info: '存入您的资产开始赚取利息',
    supply_rate_description: '年化率将根据市场供应和需求变化',
    withdraw_info: '从您的Compound资产中提现',
    borrowing_asset: '您当前正在借入该资产',
    borrowing_asset_description: '当前仅对存入的Dai资产支持CDP交互',
    repay_cdp_debt: '通过花费您在Compound中地Dai资产来偿还您的CDP债务',
    generate_dai_cdp: '从CDP中获得Dai利息并存入到您的Compound资产',
    enable_borrow: '开启借款',
    enable_borrow_description: '为了开始借入资产，您首先必须启用借款功能 。建议只开启想要借入资产的借入功能，否则以后会增加Compound交互交易的gas费用',
    repay_info: '用您帐户中的资产偿还您的借款',
    borrow_info: '从Compound中借入资产，你需要在借款前存入资产作为抵押',
    borrowing_power: '借款能力:',
    borrowing_description: '借款金额+借款利息',
    borrow_rate_description: '借款利率将随市场供应和需求变化',
    no_supply_no_borrow: '您目前没有存入或借贷任何资产',
    no_supply_no_borrow_description: ' 您可以存入资产以赚取利息，也可以将其抵押以借入其他资产。这是通过Compound v2协议实现的，您可以在FAQ中找到更多信息',
    interest_owed: '借款利息',
    interest_estimate_info: '根据当前利率估算',
    interest_owed_description: '借款利息总额',
    interest_estimate: '预估利息:',
    interest_earned: '已赚取利息',
    interest_earned_description: '赚取利息总额',
  },
  savings: {
    balance: '这是您在所有交互协议中的总余额，包括到目前赚到的利息',
    average_interest_rate: '这是根据您在每个协议存入的Dai数量计算的当前平均利率',
    curr_average_interest_rate: '当前平均利率:',
    user_wallet_description: '为了使用我们的储蓄功能，您首先需要创建一个用户钱包。 这将是您的个人合约钱包，您可以同时使用高级功能并随时提现。请注意，储蓄功能中使用的任何资金在其他面板（如Compound）上均不可见',
    import_description: '我们的导入功能使您可以通过用户钱包（DSProxy），通过一次交易，就可将当前提供的资产再次存入到智能储蓄中的同一协议',
    import_modal_description: '我们检测到您已经向一种受支持的协议存入了资产 您想将这些资产导入智能储蓄吗？',
  },
  homepage: {
    defi_dashboard: '您的DeFi面板',
    defi_saver_management: 'DeFi Saver是分布式金融协议的一站式管理解决方案',
    go_to_dashboard: '前往面板',
    defi_saver_you_can: '通过DeFi Saver你可以:',
    boost_repay: '加仓&还款',
    boost_repay_description: '通过单次交易增加您的MakerDAO CDP ETH杠杆或者减少您的Dai债务',
    automate_cdp: '自动化CDP抵押率管理',
    automate_cdp_description: '配置自动化清算保护或者按目标抵押率自动增加杠杆.',
    interact_compound_makerdao: '在Compound和MakerDAO之间交互',
    interact_compound_makerdao_description: '通过一次交易直接将CDP中的Dai添加到Compound资产或者用Compound中资产偿还CDP债务',
    earn_conveniently: '赚钱更方便',
    earn_conveniently_description: '通过一次交易直接将CDP中的Dai添加到Compound资产或者用Compound中资产偿还CDP债务',
    manage_defi_portfolio: '管理您的DeFi投资组合',
    simple_advanced_features: '让高级功能变得简单',
    defi_saver_supports: 'DeFi Saver支持',
    decentralized_exchanges: '去中心化交易所',
    eth_dai_liquidity: 'ETH和Dai的流动性来自多个去中心化交易所',
    manage_protocols: '在单个应用中管理各种最流行的DeFi协议',
    supported_wallets: '支持MetaMask、硬件和移动钱包',
    compatible_dashboards: 'DeFi Saver与MakerDAO和Compound完全兼容.无需迁移，只需简单连接您的钱包，就可以开始使用',
    try_defi_saver_today: '立即尝试DeFi Saver',
  },
  misc: {
    logging_in: '登录中，请等待...',
    connecting_provider: '连接web3提供商, 请等待...',
    getting_cdp: '获取您的CDP, 请等待...',
    insurace_label: '%currency 担保 %sumAssured 直到 %validUntil',
    exchange_slippage: '进行重置，若波动超过:',
    exchange_for: '将 %from 兑换成 %to',
    exchange_disclaimer: '根据Kyber, Uniswap和eth2dai预估的最佳价格。包括 0.25% 的服务费',
    exchanging_funds: '兑换您的资产...',
    copied_to_clipboard: '复制到剪贴板',
    short_description: '做空功能将借入选中的代币并兑换为一种稳定币。整个过程将通过一次点击和一次交易完成该功能即将推出，尽请期待',
    leverage_description: ' 杠杆功能将会借入一种稳定币并兑换为您想做杠杆的代币。整个过程将通过一次点击和一次交易完成该功能即将推出，尽请期待',
    non_web3: '非web3浏览器',
    web3_browser_info: '为了使用DeFi Saver并与区块链交互，你需要一款支持Web3的浏览器，我们推荐您使用CoinBase、Trust、Opera或者Status',
    earned_since_compound: '距上次访问，您已赚取:',
    contact_us_info: '如果您有任何疑问或建议，请随时使用下面的联系表与我们联系 我们会尽快与您联系',
    feature_in_development: '此功能目前正在开发中',
    subscribe_notifications: '您可以在下方订阅，便于您在通知上线后立即收到通知',
    subscribe_success: '感谢您的订阅！我们会在功能上线后立即通知您',
    confirm_transaction: '请确认您的交易',
    tx_sent: '交易 %txHash 已经被创建，目前正在处理中',
    tx_confirmed: '交易 %txHash 完成',
    transaction_settings: '交易设置',
    fast: '较快',
    regular: '普通',
    cheap: '较慢',
    gas_price: 'Gas价格',
    gas_limit: 'Gas上限',
    total_price: '总费用:',
  },
  errors: {
    error_occurred: '发生错误',
    close_cdp: '关闭CDP需要偿还所有Dai和MKR债务。关闭CDP后，您将无法再与其进行交互',
    required: '必填',
    over_max: '数值大于最大值',
    under_zero: '数值不能小于0',
    no_value: '没有输入数值',
    invalid_value: '%value 不可用',
    positive_value: '必须为正数',
    must_be_over: '必须大于%value ',
    wallet_not_connected: '钱包未连接',
    not_supported: ' 当前尚未支持 %item ',
    compound_cdp_interaction: 'CDP交互目前只支持Dai资产',
    nothing_supplied: '未存入任何资产',
    asset_supplied: '您目前正在存入该资产，您不能同时存入和借入同一资产。如果您想借入该资产，请先将你存入的该资产进行提现',
    asset_borrowed: '您目前正在借入该资产，您不能同时存入和借入同一资产。如果您想存入同一资产，请先偿还您借入的该资产',
    swap_same_project: '您不能在同一项目之间进行交换',
    no_mkr_tokens: '您没有Mkr代币来支付稳定债务',
    no_dai_payback: '您目前没有足够的Dai来偿还CDP债务',
    no_dai_close_cdp: '您目前没有足够的Dai来关闭CDP',
    no_local_storage_state: '没有本地存储状态',
    no_ledger_item: '没有上次使用的分类帐项目',
    wrong_network: '网络错误-请将 %type 网络设置为 %network 网络',
    provider_not_approved: '供应商未预先批准',
    denied_login: '您已拒绝登录',
    denied_transaction: '你已拒绝该交易',
    email_fail: '无法发送邮件',
    user_denied_tx: '用户拒绝发送',
    not_enough_funds: '资金不足，无法完成交易',
    tx_repeat: '检测到重复交易',
    tx_cancel: '交易已取消',
    compound_tx_fail: 'Compound交易失败',
    no_accounts_locked: '没有账号，可能已锁定',
    unknown_network: '未知网络',
    ledger_locked: '分类账单已锁定',
    ledger_contract_data: '请在您的分类账单中开启合约数据功能',
    user_canceled: '用户已取消交易',
    automatic_trigger: '操作将触发自动储蓄',
    no_wallet: '未检测到钱包',
    connect_access: '连接您的钱包以访问此页',
    over_value: '必须超过 %value',
    value_less_than: '数值必须小于 %label',
    target_limit_difference: '目标比率和限制比率之差必须超过 %value%',
    positive_number: '必须为正数',
    page_not_found: '页面未找到',
  },
  pages: {
    terms_of_service: '服务条款',
    faq: '常见问题解答',
    compound: 'Compound',
    smart_savings: '智能储蓄',
    maker_dao_cdp: 'MakerDAO CDP',
    privacy_policy: '隐私政策',
  },
};


questions：
1.legacy: 'Legacy',
2.token_amount_in: '%first_token amount in %second_token:'
3.insurace_label: 'Insured for %sumAssured %currency until %validUntil'
4.How to deal with words beginning with '%'?
